### ISSUE TITLE
Rammstein 

### ISSUE THREAD

**Issue by MagicBusX** [RoboLask/kardana_music_repo#1]
Rammstein is an industrial metal band, not rock

**Comment by RoboLask** [comment]
Rammstein is a German rock band formed in January 1994. Their musical style combines elements of industrial metal and the traditions of the German heavy scene (Neue Deutsche Härte). Rammstein is one of the most popular rock bands in Germany, widely known in Europe and the USA.

**Comment by MagicBusX** [comment]
https://en.m.wikipedia.org/wiki/List_of_industrial_metal_bands
There is Rammstein here

**Comment by igorhg-ctrl** [comment]
yes, but their songs have more rock elements
